export const GET_EXAMPLES = 'GET_EXAMPLES';
export const GET_EXAMPLES_REQUEST = 'GET_EXAMPLES_REQUEST';
export const GET_EXAMPLES_FAILURE = 'GET_EXAMPLES_FAILURE';

export const GET_EXAMPLE = 'GET_EXAMPLE';
export const GET_EXAMPLE_REQUEST = 'GET_EXAMPLE_REQUEST';
export const GET_EXAMPLE_FAILURE = 'GET_EXAMPLE_FAILURE';
